### ISSUE TITLE
Heat Index tells me -9999 no matter what I choose

### ISSUE THREAD

**Issue by clymerrm** [craigmichaelmartin/weather-app--ash#1]
Or -5573 celsius

**Comment by craigmichaelmartin** [comment]
Thanks for catching that! I didn't notice the wunderground note:
> Note that values will = -9999 or -999 for Null or Non applicable (NA) variables.

I've [updated](https://github.com/craigmichaelmartin/weather-app--ash/commit/ed6affc10a8f73bef5a205bad2fb5a0240b3306d) to account for these values.
