### ISSUE TITLE
"The data provided was invalid. Day must be within ten days of today." message when accessing through URL

### ISSUE THREAD

**Issue by willmooney3** [craigmichaelmartin/weather-app--ash#2]

**Comment by craigmichaelmartin** [comment]
This alert is shown when trying to access days in the past or too far in the future. You may have re-hit a url from the past with an old date/time. I have thought about changing the url mapping to 
```
/<zip>/today(+<dayOffset>)/now(+<hourOffset>)/<scale>
```
so,  `/44024/today` (for today) or `/44147/today+7/now+1/metric` (for next week in an hour), but am torn as to whether it's better, or just different. It would solve this problem of bookmarking / re-hitting routes from the past. Let me know what you think.

**Comment by will-mooney-3** [comment]
Issue resolved from the URL I was hitting it from.

I think that's just different, not necessarily better.
